const states = {
  names: {
    SP: 'Rondônia',
    RJ: 'Acre',
    DF: 'Amazonas',
    RS: 'Roraima',
    PE: 'Pará',
    MG: 'Amapá',
    PR: 'Tocantins',
    SC: 'Maranhão',
    ES: 'Piauí',
    CE: 'Ceará',
    GO: 'Rio Grande do Norte',
    MS: 'Paraíba',
    SE: 'Pernambuco',
    BA: 'Alagoas',
    AL: 'Sergipe',
    AM: 'Bahia',
    RN: 'Minas Gerais',
    RO: 'Espírito Santo',
    PB: 'Rio de Janeiro',
    PI: 'São Paulo',
    MA: 'Paraná',
    TO: 'Santa Catarina',
    AP: 'Rio Grande do Sul',
    PA: 'Mato Grosso do Sul',
    MT: 'Mato Grosso',
    RR: 'Goiás',
    AC: 'Distrito Federal',
  },
  codes: {
    SP: 35,
    RJ: 33,
    DF: 53,
    RS: 43,
    PE: 26,
    MG: 31,
    PR: 41,
    SC: 42,
    ES: 32,
    CE: 23,
    GO: 52,
    MS: 50,
    SE: 28,
    BA: 29,
    AL: 27,
    AM: 13,
    RN: 24,
    RO: 11,
    PB: 25,
    PI: 22,
    MA: 21,
    TO: 17,
    AP: 16,
    PA: 15,
    MT: 51,
    RR: 14,
    AC: 12,
  },
  objectIds: {
    AC: 'AC',
    AL: 'AL',
    AP: 'AP',
    AM: 'AM',
    BA: 'BA',
    CE: 'CE',
    DF: 'DF',
    ES: 'ES',
    GO: 'GO',
    MA: 'MA',
    MG: 'MG',
    MS: 'MS',
    MT: 'MT',
    PR: 'PR',
    PB: 'PB',
    PA: 'PA',
    PE: 'PE',
    PI: 'PI',
    RN: 'RN',
    RS: 'RS',
    RJ: 'RJ',
    RO: 'RO',
    RR: 'RR',
    SC: 'SC',
    SE: 'SE',
    SP: 'SP',
    TO: 'TO',
  },
};

module.exports = states;
