const states = {
  names: {
    11: 'Rondônia',
    12: 'Acre',
    13: 'Amazonas',
    14: 'Roraima',
    15: 'Pará',
    16: 'Amapá',
    17: 'Tocantins',
    21: 'Maranhão',
    22: 'Piauí',
    23: 'Ceará',
    24: 'Rio Grande do Norte',
    25: 'Paraíba',
    26: 'Pernambuco',
    27: 'Alagoas',
    28: 'Sergipe',
    29: 'Bahia',
    31: 'Minas Gerais',
    32: 'Espírito Santo',
    33: 'Rio de Janeiro',
    35: 'São Paulo',
    41: 'Paraná',
    42: 'Santa Catarina',
    43: 'Rio Grande do Sul',
    50: 'Mato Grosso do Sul',
    51: 'Mato Grosso',
    52: 'Goiás',
    53: 'Distrito Federal',
  },
  codes: {
    35: 'SP',
    33: 'RJ',
    53: 'DF',
    43: 'RS',
    26: 'PE',
    31: 'MG',
    41: 'PR',
    42: 'SC',
    32: 'ES',
    23: 'CE',
    52: 'GO',
    50: 'MS',
    28: 'SE',
    29: 'BA',
    27: 'AL',
    13: 'AM',
    24: 'RN',
    11: 'RO',
    25: 'PB',
    22: 'PI',
    21: 'MA',
    17: 'TO',
    16: 'AP',
    15: 'PA',
    51: 'MT',
    14: 'RR',
    12: 'AC',
  },
  objectIds: {
    uTN8WP10HY: 'AC',
    XHUDIFEjQy: 'AL',
    kfOtyvDHh3: 'AP',
    kZjftVxsJ2: 'AM',
    alzUcJAbsL: 'BA',
    ThJDLoQlin: 'CE',
    U8jHH89IkZ: 'DF',
    LlLUQQW7em: 'ES',
    MOPNB3fPnM: 'GO',
    fwHJWgSphk: 'MA',
    '2v59GBInrd': 'MG',
    EgBxJSFJkf: 'MS',
    EPgf4v3eYo: 'MT',
    cSB7DrlxKW: 'PR',
    '6eSlyH3T4n': 'PB',
    d1ejs3xsWl: 'PA',
    fnVKeAvGLb: 'PE',
    gQiBOengLe: 'PI',
    ZEqcJDbUUk: 'RN',
    zWseWwWhhn: 'RS',
    SgfpOQHx9r: 'RJ',
    IeCnkqtfOf: 'RO',
    OpUETQp72a: 'RR',
    v64fT2DVSw: 'SC',
    VpSNd1zJrg: 'SE',
    AIzthCzqdx: 'SP',
    bsZ2atdJ6V: 'TO',

  },
};

module.exports = states;
